# Generated by Django 5.0.7 on 2024-07-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_categorie_options_alter_record_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='city',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='record',
            name='country',
        ),
        migrations.RemoveField(
            model_name='record',
            name='email',
        ),
        migrations.RemoveField(
            model_name='record',
            name='province',
        ),
        migrations.AddField(
            model_name='record',
            name='tall',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='phone',
            field=models.IntegerField(max_length=20),
        ),
    ]
