# Generated by Django 5.0.7 on 2024-07-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_record_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='tall',
            field=models.IntegerField(),
        ),
    ]
